name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Create Tarball
        run: |
          tar -czvf cogpilot.jl-${{ github.ref_name }}.tar.gz \
            --exclude='.github' \
            --exclude='.git*' \
            .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: cogpilot.jl-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
